### ISSUE TITLE
To-do list for finalizing manuscript

### ISSUE THREAD

**Issue by ChloeRN** [ChloeRN/VredfoxIPM#74]
Below is a checklist of tasks that need taking care of in different time-windows. Unless otherwise indicated, @stijnhofhuis will be in charge of the tasks. 

**Before sharing MS with remaining co-authors**
- [x] review Chloé's text edits/changes
- [x] edit "Study species and area" section according to comments
- [x] check out the "new" rodent scenarios + interpretation (cycles now included)

**While co-authors review text**
- [x] Check out and take up Chloé's remaining queries in text (_Stijn & Doro_)
- [x] Draft abstract
- [x] Draft cover letter
- [x] Cut down on number of references
- [x] Add/find missing references
- [x] Make figure: spatial representation of all data
- [x] Make figure: time series of rodent and reindeer data
- [x] Make figure & function : decomposition of natural mortality variation into covariates & random (#73)
- [x] Make table & function: post-hoc parameter correlations (#73)  
- [x] Make a list of things that still need to be discussed
- [x] Plan a meeting Chloe, Doro, Stijn, to discuss any still open queries / feedback from co-authors?

**Before submission**
- [x] Have a meeting to discuss and resolve any still open queries / feedback from co-authors
- [x] Make figures nice (details) and refer to correctly in text
- [x] Revise & complete workflow schematic (_Chloé_)
- [x] Decide on a title (_Stijn, Chloé, Doro_)
- [x] Finalize journal choice (_Stijn, Chloé, Doro_)
- [x] Shorten manuscript (if necessary, _Chloé & Stijn_)
- [x] Update README & write vignette for code repository (_Chloé_)
- [x] Version & archive code (_Chloé_)
- [x] Review authorship statement (_everyone_)
- [x] Set up OSF storage
- [x] Make sure data references are complete & correct
- [x] Double-check all figure references are correct (_Stijn_)
- [x] Make a list of potential reviewers (_everyone_)
- [x] Download manuscript and add missing references from zotero (_Stijn_)
- [x] add last metadata on genetic prob text file OSF (_Stijn_)
- [x] fill in readme OSF (_Stijn_)
- [x] how to access coat dataportal and reference (Stijn)

**Comment by ChloeRN** [comment]
For setting up the OSF storage, here are a few examples: 

[OSF | An integrated open population distance sampling approach for modelling age-structured populations](https://osf.io/bc3en/)

[OSF | Harvest sustainability assessments for ringed seals in Svalbard](https://osf.io/mtyu3/)

[OSF | An integrated open population distance sampling approach for modelling age-structured populations](https://osf.io/bc3en/)
